// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMQ8n_piD_kTHJ1fkbbwEdxgEvkTap6o',
    appId: '1:435111663397:web:8f7a3613ee4a1e63c9eccc',
    messagingSenderId: '435111663397',
    projectId: 'smart-home-e8051',
    authDomain: 'smart-home-e8051.firebaseapp.com',
    storageBucket: 'smart-home-e8051.firebasestorage.app',
    measurementId: 'G-JKQ1L1NC0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaZaQ8DEE3utcXFepmemtPIWrDgnEndSM',
    appId: '1:435111663397:android:3d95c37edaead909c9eccc',
    messagingSenderId: '435111663397',
    projectId: 'smart-home-e8051',
    storageBucket: 'smart-home-e8051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdI2Gedn8CLI_LPzWkHsl0q2-FUrlrCbQ',
    appId: '1:435111663397:ios:8d43ff0577ebb433c9eccc',
    messagingSenderId: '435111663397',
    projectId: 'smart-home-e8051',
    storageBucket: 'smart-home-e8051.firebasestorage.app',
    iosBundleId: 'com.example.projectiot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdI2Gedn8CLI_LPzWkHsl0q2-FUrlrCbQ',
    appId: '1:435111663397:ios:8d43ff0577ebb433c9eccc',
    messagingSenderId: '435111663397',
    projectId: 'smart-home-e8051',
    storageBucket: 'smart-home-e8051.firebasestorage.app',
    iosBundleId: 'com.example.projectiot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQMQ8n_piD_kTHJ1fkbbwEdxgEvkTap6o',
    appId: '1:435111663397:web:bb907c8fe3eeab61c9eccc',
    messagingSenderId: '435111663397',
    projectId: 'smart-home-e8051',
    authDomain: 'smart-home-e8051.firebaseapp.com',
    storageBucket: 'smart-home-e8051.firebasestorage.app',
    measurementId: 'G-XDXNLP1Y8E',
  );
}
